name: pakas
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  flutter_launcher_icons: ^0.11.0
  get: 4.6.5
  google_fonts: ^4.0.3
  google_sign_in: ^5.4.4
  image_picker: ^0.8.6+1
  drop_shadow: 0.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  change_app_package_name: ^1.1.0
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

